# Device
DEVICE_UDID = "ZD22243TNC"
DEVICE_NAME = "moto g51 5G"
PLATFORM_VERSION = "12"

# App
APP_PACKAGE = "com.allymobile_jates"
APP_ACTIVITY = f"{APP_PACKAGE}/.activities.SplashActivity"
APPIUM_SERVER = "http://127.0.0.1:4723"

# Timeouts
UIAUTOMATOR2_LAUNCH_TIMEOUT = 90000
UIAUTOMATOR2_INSTALL_TIMEOUT = 90000
NEW_COMMAND_TIMEOUT = 300
DEFAULT_WAIT = 10
SPLASH_WAIT = 5
POST_LOGIN_WAIT = 8

# Credentials
COMPANY = "allypro"
USERNAME = "vk77"
PASSWORD = "1234"